#data mapping
#api key
apiKey: <your-holiday-api-key>
#holiday api url
apiUrl: https://holidayapi.com/v1/holidays

server:
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 8091

# logging settings
logging:
   level: INFO
   appenders:
      - type: console